#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DIST_DIR="$ROOT_DIR/dist"
RELEASES_DIR="$ROOT_DIR/releases"
RELEASES_PAGE="$RELEASES_DIR/README.md"
PACKAGE_NAME="voxclip"

cd "$ROOT_DIR"

VERSION="$(
  uv run python - <<'PY'
import tomllib
from pathlib import Path

with Path("pyproject.toml").open("rb") as pyproject_file:
    print(tomllib.load(pyproject_file)["project"]["version"])
PY
)"
ARCHITECTURE="$(dpkg --print-architecture)"
DEB_NAME="${PACKAGE_NAME}_${VERSION}_${ARCHITECTURE}.deb"
LATEST_NAME="${PACKAGE_NAME}_latest_${ARCHITECTURE}.deb"

echo "Building ${DEB_NAME}"
uv run python packaging/build_deb.py "$@"

SOURCE_DEB="$DIST_DIR/$DEB_NAME"
if [[ ! -f "$SOURCE_DEB" ]]; then
  echo "Expected package not found: $SOURCE_DEB" >&2
  exit 1
fi

mkdir -p "$RELEASES_DIR"
cp -f "$SOURCE_DEB" "$RELEASES_DIR/$DEB_NAME"
cp -f "$SOURCE_DEB" "$RELEASES_DIR/$LATEST_NAME"

uv run python - "$RELEASES_DIR" "$RELEASES_PAGE" "$LATEST_NAME" <<'PY'
from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

releases_dir = Path(sys.argv[1])
releases_page = Path(sys.argv[2])
latest_name = sys.argv[3]
latest_path = releases_dir / latest_name
package_pattern = re.compile(r"^voxclip_(?P<version>\d+\.\d+\.\d+)_(?P<arch>[^/]+)\.deb$")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as file:
        for chunk in iter(lambda: file.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def version_key(version: str) -> tuple[int, ...]:
    return tuple(int(part) for part in version.split("."))


def size_label(path: Path) -> str:
    return f"{path.stat().st_size / (1024 * 1024):.1f} MB"


packages = []
for package_path in releases_dir.glob("voxclip_*_*.deb"):
    match = package_pattern.match(package_path.name)
    if match is None:
        continue
    version = match.group("version")
    arch = match.group("arch")
    packages.append(
        {
            "version": version,
            "arch": arch,
            "name": package_path.name,
            "size": size_label(package_path),
            "sha256": sha256(package_path),
            "sort": version_key(version),
        }
    )

packages.sort(key=lambda item: (item["sort"], item["arch"]), reverse=True)

lines = [
    "# VoxClip Releases",
    "",
    "This page is generated by `./generate_new_release.sh` from the Debian packages",
    "present in `releases/`.",
    "",
    "## Latest",
    "",
]

if latest_path.exists():
    lines.extend(
        [
            f"- Download: [{latest_name}](./{latest_name})",
            f"- SHA256: `{sha256(latest_path)}`",
            f"- Size: {size_label(latest_path)}",
            "",
        ]
    )
else:
    lines.extend(["_No latest package has been generated yet._", ""])

lines.extend(["## Available Releases", ""])

if packages:
    lines.extend(
        [
            "| Version | Architecture | Download | SHA256 | Size |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for package in packages:
        lines.append(
            "| {version} | {arch} | [{name}](./{name}) | `{sha256}` | {size} |".format(
                **package
            )
        )
else:
    lines.append("_No release packages found._")

lines.append("")
releases_page.write_text("\n".join(lines), encoding="utf-8")
PY

echo "Release package: releases/$DEB_NAME"
echo "Latest package: releases/$LATEST_NAME"
echo "Release page: releases/README.md"
